apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <body>
            <h1> I am Cloudethix Team, Are you ?!! </h1>
            Version: 1.1
    </body>
    </html>
